# site settings
title: Digitipus In Nazoo
subtitle:
description:
baseurl: "/site-digit" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Instagram: https://www.instagram.com/digitipus?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==
  Spotify: https://open.spotify.com/artist/6Tv10ke0hEJJov8I9nuJml?si=6pgxNBF0RM6Wts1eU42QKQ
  Youtube: https://www.youtube.com/@digitipusinnazoo9025
  Facebook: https://www.facebook.com/digitipusinnazoo/


# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

defaults:
  - scope:
      path: "assets/images"
  - values:
      image: true


